version: '3.4'

services:
  catalogdb: 
    image: mongo
    container_name: catalogdb
  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: CatalogAPI/Dockerfile

volumes:
  mongo_data: /data/db
